### ISSUE TITLE
Problem with #include <numpy/arrayobject.h>

### ISSUE THREAD

**Issue by OrbitalMechanic** [ester-project/ester#4]
I'm attempting to build and install ester on a desktop Mac Pro (Late 2013) running Mac OS X Sierra ver. 10.12.6 with the Anaconda Distribution of Python 3.6 installed.

I was able to complete the configure step, but I did get warnings concerning HDF5, see the attached file to this posting. Seeing that I had no further errors, I proceeded onto the make step, where I encountered a fatal error in compiling ../../src/graphics/matplotlib.cpp. The error message was

**../../src/graphics/matplotlib.cpp:4:10: fatal error: 'numpy/arrayobject.h' file not found**

From the offending statement

**#include <numpy/arrayobject.h>**

where is the numpy subdirectory that contains arrayobject.h resides?

Please advise,

Sam Dupree.
[ester-master_build_make_log.txt](https://github.com/ester-project/ester/files/1648690/ester-master_build_make_log.txt)

**Comment by bputigny** [comment]
Hello Samuel,

It seems that you don't have python-config installed, which could lead to the issue you are encountering. The file 'arrayobject.h' should be located in something like 'numpy/core/include/numpy' in your python distribution. From what I saw in your config.log, it should be in '/Users/user/anaconda3/lib/python3.6/site-packages'. So adding CPPFLAGS="-I/Users/user/anaconda3/lib/python3.6/site-packages/numpy/core/include/" should do the job.
Hope this helps,
Best,
Bertrand

**Comment by OrbitalMechanic** [comment]
Bertrand,

Thanks for responding to my post.

The Anaconda Distribution for Python 3.6 does not install python-config. 
Instead, the Anaconda Distribution installs python3-config and 
python3.6-config both aliased to 
Users/user/anaconda3/bin/python3.6m-config. Will this be a problem?

Sam Dupree.

**Comment by bputigny** [comment]
This should also be fixed with d0e2a9feecc2122162e4e234de830f54fa258ef3.
