### ISSUE TITLE
What is the procedure to build/install ester_build?

### ISSUE THREAD

**Issue by OrbitalMechanic** [ester-project/ester#6]
I was attempting to build star1R and star2R in the ~/ester/utils/starR directory. The problem I'm having is that the Makefile cannot find $(ESTER_DIR)/bin/ester_build, where $(ESTER_DIR) is set to ../.. within the Makefile.

The build and installation of ester did not install ester_build, although the build/install was successful and that ester_build is referenced in the current ESTER User's Guide.\

Please advise.

Sam Dupree.

**Comment by bputigny** [comment]
Commits acb0411a2b3e1aee1e0786299759a7bc07b81f09 and 0f0bbed080d136ce845c46d929f363cf096adeaf should fix your issue: now the utilities star1dR and star2dR are built by default. After a successful `make install`, you should have access to these utilities in the bin directory of the install directory of ester.
