### ISSUE TITLE
ImportError: No module named 'ester'

### ISSUE THREAD

**Issue by ostiavamos** [ester-project/ester#8]
Hi!! 
Im new in ESTER. Im following the ESTER User's Guide and I having a problem at the secction 2.9.1 . (Using ESTER Native format) When I try to import the module ester i get this

>>> from ester import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ester'

I have looked the modules I have in python, and there isnt any ester one. 
The file ester.in does exist at ester/python directory though 
Any sugestion how i get it?
Thanks!!

**Comment by rieutord** [comment]
Hi,

the problem most likely comes from your PYTHONPATH. You should do some 
setting like:

setenv PYTHONPATH $HOME/Ester/local/lib/python2.7/dist-packages/

or analog setup if in bash.

hope this helps,

Michel

*****************************************************************************
Prof. Michel Rieutord
Institut de Recherche en Astrophysique et Planétologie
Université Paul Sabatier et Observatoire Midi-Pyrénées
email : Michel.Rieutord@irap.omp.eu
14 avenue Edouard Belin                 Tel +33 -(0)5 61 33 29 49
31400 Toulouse, France                  Fax +33 -(0)5 61 33 28 40
*****************************************************************************

Le 17/02/2020 à 04:16, ostiavamos a écrit :

**Comment by ostiavamos** [comment]
Thnaks Michele,it worked!! ( I did: export PYTHONPATH=$/home/usuario/ester/local/lib/python3/dist-packages)
But I having  another error message when I try to load one of the models from postprocessing directory
>>> import sys
>>> from ester import *
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> A=star1d('HR.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'star1d' is not defined

Thanks for your help!

**Comment by rieutord** [comment]
It may be that your path is lacking the binary files; check the path and
see if it contains something like ester/local/bin/

Michel

*****************************************************************************
Prof. Michel Rieutord
Institut de Recherche en Astrophysique et Planétologie
Université Paul Sabatier et Observatoire Midi-Pyrénées
email : Michel.Rieutord@irap.omp.eu
14 avenue Edouard Belin                 Tel +33 -(0)5 61 33 29 49
31400 Toulouse, France                  Fax +33 -(0)5 61 33 28 40
*****************************************************************************

Le 18/02/2020 à 00:40, ostiavamos a écrit :

**Comment by ostiavamos** [comment]
Also worked!
Thanks!
